// Contenido de respaldo. Se usa si Supabase no está configurado o no responde.
// La fuente oficial es la base de datos (se edita desde /admin).
// Los mismos datos están en supabase/02-datos-iniciales.sql.

const I = "assets/";

export const LOCAL = {
  ajustes: {
    hero_texto: "Misiones, batallas, monumentos y memoria viva: cada capítulo es una parada en el tiempo. Elige tu destino y despega.",
    nosotros_intro: "La Corporación Tame, Historia y Cultura, reúne investigación, patrimonio y participación para que la memoria local permanezca accesible y viva.",
    mision: "Investigar, preservar, proteger y divulgar la historia, el patrimonio y las expresiones culturales de Tame, conectando el conocimiento institucional con la participación de la comunidad.",
    vision: "Ser referente en la conservación de la memoria, la identidad y el patrimonio de Tame, con una ciudadanía que conoce, valora y comparte su historia.",
    valores: "Coherencia, responsabilidad, honestidad, rigor investigativo y transparencia en el manejo administrativo.",
    objetivos: "Desarrollar proyectos de investigación cultural.\nAsesorar a gobiernos en proyectos socioculturales.\nOrganizar conferencias y seminarios sobre el Llano.\nPromover la clasificación de archivos históricos.\nFundar una revista de investigación.\nEstimular una conciencia ciudadana sobre la historia regional.",
    aporte_texto: "Una fotografía, una carta, un relato de los abuelos. Cada aporte se revisa y cataloga antes de entrar al archivo digital.",
    facebook: "https://facebook.com/turistame",
    instagram: "https://instagram.com/turistame",
    correo: "contacto@corporaciontame.org",
    ubicacion: "Tame, Arauca · Colombia"
  },

  columnas: [
    { edicion: null, fecha: "2026-09-23T15:00:00-05:00", categoria: "Infraestructura regional", autor: "Leonel Pérez Bareño", cargo: "Columnista", titulo: "Socializar las propuestas para mejorarlas y lograr su apoyo definitivo", entradilla: null, cuerpo:
      "Esta tarde del miércoles 23 de septiembre del 2026 expondré en el teatro La Vorágine de Villavicencio mis propuestas sobre los desafíos financieros del sistema vial llanero. Allí me referiré a la infraestructura carreteable, fluvial y aérea del territorio llanero.\n\nMostraré el atraso relativo del Meta con relación a Arauca y Casanare en términos de vías pavimentadas, no obstante sus enormes ingresos de regalías. Aludiré a los diez primeros aeropuertos de la región. Señalaré los problemas de los principales ríos locales. Insistiré en la necesidad de la integración regional orinoquense y, finalmente, plantearé mi propuesta de financiamiento sobre la base de transformar el actual sistema de regalías.\n\nRecibiremos (Meta, Casanare, Arauca) 52 billones de pesos de regalías en los próximos veinte años. Pues bien, dediquemos la mitad, el 50 % de este recurso, al Fondo Vial del Llano. Con tal cantidad (26 billones de pesos) construiríamos la TOTALIDAD de las vías de Arauca, Casanare, Meta y Vichada. Son 15 vías que suman 1.600 km, incluyendo dos puentes sobre el río Meta y el aeropuerto del Piedemonte araucano: ARPA, Aeropuerto Regional del Piedemonte Araucano.\n\nEn síntesis, se requieren 4 billones de pesos para Arauca, 6 para Casanare, 7 para Vichada y 9 para Meta. Esto último incluye la solución de los cien puntos críticos de la Autopista Bogotá-Villavicencio y la vía Uribe-Colombia." },
    { edicion: null, fecha: "2026-09-21T15:00:00-05:00", categoria: "Desarrollo económico", autor: "Leonel Pérez Bareño", cargo: "Columnista", titulo: "Aceite de palma rumbo al mar Atlántico", entradilla: null, cuerpo:
      "Un mil cien (1.100) km toma el trayecto Villavicencio-Barranquilla, vía Bogotá, frente a 800 km entre Villavicencio y La Ceiba, puerto en el Lago de Maracaibo, por la Troncal del Llano que pasa por Yopal, Tame y Saravena. Diferencia sustancial. Recuérdese que Meta y Casanare son los grandes productores de aceite de palma de Colombia, con un aporte superior al 70 % del total nacional.\n\nUn trancón fácil de resolver obstaculiza esta ruta de oro para el Piedemonte llanero: el puente internacional en Puerto Contreras sobre el río Arauca, en el área de la isla del Charo. Se trata de un puente muy pequeño, de solo 250 metros, que exige acuerdos binacionales hoy difíciles y mañana muy fáciles, cuando se logre la estabilización democrática de Venezuela.\n\nConviene prepararnos para esta oportunidad, pues nuestro aceite es bienvenido en Estados Unidos, Europa y Asia, además del Caribe y Centroamérica, y, como todos sabemos, el transporte marítimo es el más barato del mundo. Esta opción requiere la nacionalización del tramo Hato Corozal-Tame, lo cual acarrea un trámite muy sencillo ante el DNP." }
  ],

  monumentos: [
    { orden: 1, titulo: "Bolívar y Santander", lugar: "Plaza · Tame", imagen: I + "m-bolivar-santander.jpeg", alt: "Esculturas de Simón Bolívar y Francisco de Paula Santander sentados frente a frente", descripcion: "Recuerda el encuentro de 1819 en Tame entre Simón Bolívar y Francisco de Paula Santander, que unió a las tropas en la campaña libertadora." },
    { orden: 2, titulo: "Busto de Santander", lugar: "Monumento · Tame", imagen: I + "m-santander.jpeg", alt: "Busto de Francisco de Paula Santander", descripcion: "Homenaje a Francisco de Paula Santander en su faceta de coronel al mando del ejército, frente a la resistencia de los soldados llaneros a ser dirigidos por un militar ajeno a la región." },
    { orden: 3, titulo: "Piedra Esculpida · Ruta Bolívar", lugar: "Parque central", imagen: I + "m-piedra.jpeg", alt: "Piedra esculpida de la Ruta Bolívar", descripcion: "Monumento de honor junto al parque central, con las fechas talladas en que el General Simón Bolívar pasó por el municipio de Tame." },
    { orden: 4, titulo: "Monumento al Ejército Patriota", lugar: "Memoria pública", imagen: I + "m-ejercito.jpeg", alt: "Monumento al Ejército Patriota", descripcion: "Simboliza la unión en Tame de las tropas de Bolívar y Santander, que formaron el Ejército Patriota que marcharía hacia la liberación del país." },
    { orden: 5, titulo: "Inocencio Chincá", lugar: "Héroes de la libertad", imagen: I + "m-chinca.jpeg", alt: "Monumento a Inocencio Chincá", descripcion: "Homenaje al joven lancero indígena tameño que luchó con valentía y dio su vida por la libertad en la Batalla del Pantano de Vargas." },
    { orden: 6, titulo: "Indio Girara", lugar: "Pueblos originarios", imagen: I + "m-girara.jpeg", alt: "Monumento al indio Girara", descripcion: "Rotonda y placa en memoria de los Giraras, de la familia Arawak, pobladores originarios que dieron origen a Tame." },
    { orden: 7, titulo: "Iglesia Nuestra Señora de la Asunción", lugar: "Arquitectura religiosa", imagen: I + "m-iglesia.jpeg", alt: "Iglesia Nuestra Señora de la Asunción de Tame", descripcion: "Templo principal del municipio. La parroquia de Nuestra Señora de Tame fue erigida el 26 de abril de 1661." },
    { orden: 8, titulo: "Mujer Tameña", lugar: "Identidad", imagen: I + "m-mujer.jpg", alt: "Monumento a la Mujer Tameña", descripcion: "Celebra la fuerza, el trabajo y el papel fundamental de las mujeres tameñas en la construcción de la vida comunitaria." },
    { orden: 9, titulo: "Monumento a los Caballos", lugar: "Cultura llanera", imagen: I + "m-caballos.jpg", alt: "Monumento a los caballos", descripcion: "Evoca la relación entre el caballo, el paisaje llanero y las historias de movilidad, trabajo y libertad que definen a Tame." }
  ],

  hitos: [
    { orden: 1, anio: "1625–1628", etapa: "Misiones jesuitas", titulo: "Primera entrada jesuita", texto: "Primeras entradas de la Compañía de Jesús al territorio de los Giraras, antecedente de la fundación histórica de Tame.", imagen: I + "p-3.jpeg", encuadre: "center 60%" },
    { orden: 2, anio: "1629", etapa: "Fundación", titulo: "Fundación de La Palma de Espinosa", texto: "El 18 de febrero se funda la ciudad de La Palma de Espinosa. Entre febrero y junio se realiza la reducción del pueblo de indios de Tame.", imagen: I + "p-4.jpg", encuadre: "center" },
    { orden: 3, anio: "1637", etapa: "Fundación", titulo: "Destrucción de la ciudad", texto: "La ciudad es destruida y muere su fundador.", imagen: I + "p-2.jpeg", encuadre: "center 70%" },
    { orden: 4, anio: "1637–1647", etapa: "Pueblos originarios", titulo: "Persecución y dispersión de los Giraras", texto: "D. Martín de Mendoza persigue y dispersa a los Giraras, que se asientan en las orillas del río Arauca asistidos por Párraga.", imagen: I + "m-girara.jpeg", encuadre: "center" },
    { orden: 5, anio: "1647", etapa: "Pueblos originarios", titulo: "Reasentamiento de los Giraras", texto: "Los Giraras regresan al primitivo asentamiento de la reducción de Tame.", imagen: I + "p-rio.jpeg", encuadre: "center" },
    { orden: 6, anio: "1650", etapa: "Organización colonial", titulo: "Curato de Tame y San Miguel de Punapuna", texto: "Se establece el curato de Tame con el clérigo Damián Ugarte y se funda San Miguel de Punapuna, entre Tame y Casanare. El gobernador Alonso Sánchez Chamorro, de Antequera, interviene en la Real Audiencia.", imagen: I + "p-3.jpeg", encuadre: "center 60%" },
    { orden: 7, anio: "1657", etapa: "Organización colonial", titulo: "Hernando de Ortiz, teniente de corregidor", texto: "Hernando de Ortiz asume como teniente de corregidor de Tame.", imagen: I + "p-4.jpg", encuadre: "center" },
    { orden: 8, anio: "1659", etapa: "Misiones jesuitas", titulo: "Segunda entrada de la Compañía de Jesús", texto: "Los jesuitas regresan al territorio e inician una nueva etapa misional.", imagen: I + "p-2.jpeg", encuadre: "center 70%" },
    { orden: 9, anio: "1661", etapa: "Organización colonial", titulo: "Erección de la Parroquia Nuestra Señora de Tame", texto: "El 26 de abril de 1661 se erige la parroquia de Nuestra Señora de Tame.", imagen: I + "m-iglesia.jpeg", encuadre: "center" },
    { orden: 10, anio: "1661–1663", etapa: "Pueblos originarios", titulo: "Nuevas reducciones indígenas", texto: "Reducción de Tunebos en Pilar de Patute, Airicos en San Javier de Macaguane y Achaguas en San Salvador del Puerto.", imagen: I + "p-rio.jpeg", encuadre: "center" },
    { orden: 11, anio: "1662", etapa: "Misiones jesuitas", titulo: "Creación de la Hacienda Caribabare", texto: "Se crea la Hacienda Caribabare.", imagen: I + "p-4.jpg", encuadre: "center" },
    { orden: 12, anio: "1715", etapa: "Pueblos originarios", titulo: "Reducción de los Betoyes", texto: "Reducción de indios Betoyes en San Ignacio, a orillas del río Tame.", imagen: I + "p-3.jpeg", encuadre: "center 60%" },
    { orden: 13, anio: "1767", etapa: "Misiones jesuitas", titulo: "Expulsión de los jesuitas", texto: "La expulsión de la Compañía de Jesús transforma el curso de las misiones y de los asentamientos de la región.", imagen: I + "p-2.jpeg", encuadre: "center 70%" },
    { orden: 14, anio: "1819", etapa: "Independencia", titulo: "Tame, Cuna de la Libertad", texto: "Formación de la República de Colombia. El encuentro de Bolívar y Santander en Tame, junto con la entrega de tropas de Fray Ignacio Mariño, marca la campaña libertadora.", imagen: I + "m-bolivar-santander.jpeg", encuadre: "center" }
  ],

  publicaciones: [
    { orden: 1, volumen: null, titulo: "Tame, 400 años", subtitulo: "Demografía histórica, sociedad y familia", tipo: "Demografía histórica", texto_lomo: "TAME, 400 AÑOS", portada: I + "libro-tame400.jpeg", contraportada: I + "libro-tame400-back.jpeg", lomo: I + "lomo-tame400.jpeg", color_lomo: "#cfcfcb", color_tinta_lomo: "#1c1c1c", grosor: 30, autores: "Luis Milciades Pérez González, Julio César Lamus Gélvez y Juan Jacobo Carrizales Casas.", descripcion: "La serie «Tame, 400 años» corresponde a una línea de investigación que realiza un grupo de profesionales de la Corporación Tame, Historia y Cultura. Los hallazgos y resultados de dichos estudios, sobre los acontecimientos sociales, políticos, económicos, culturales y ambientales ocurridos en el actual territorio de Tame, se publican ad portas de conmemorar su cuatricentenaria existencia.\\n\\nEn este libro, Tame, 400 años. Demografía histórica, sociedad y familia, sus autores, miembros de la Corporación Tame, Historia y Cultura, plantean las transformaciones que desde el siglo XVII se fueron dando en este territorio: su poblamiento como pueblo de indios, su demografía histórica y los apellidos que había en los orígenes de Tame (siglos XVII–XVIII).\\n\\nAsimismo, abordan su desarrollo y sus conflictos sociales y económicos entre 1900 y 1950: ¿Quiénes somos?, con algunos «apuntes de aproximación a la génesis de nuestro pueblo»." },
    { orden: 2, volumen: null, titulo: "De Macaguán a Corocito", subtitulo: "Historia jesuita en los Llanos de Tame, 1661–2026", tipo: "Historia misional", texto_lomo: "DE MACAGUÁN A COROCITO", portada: I + "libro-macaguan.jpeg", contraportada: I + "libro-macaguan-back.jpeg", lomo: null, color_lomo: "#4b1e2b", color_tinta_lomo: "#e8c66f", grosor: 20, autores: "Julio César Lamus Gélvez y Luis Milcíades Pérez González.", descripcion: "Este libro reúne, bajo un solo marco narrativo, más de veinte años de investigación sobre la historia del territorio de Macaguán-Corocito, en el municipio de Tame, departamento de Arauca.\\n\\nSus autores, Julio César Lamus Gélvez y Luis Milciades Pérez González, son historiadores regionales con vínculos familiares y biográficos directos con el territorio que describen, lo que confiere a su escritura una dimensión de testimonio que complementa —y a su vez trasciende— el rigor documental.\\n\\nLa obra fue concebida como un libro de historia regional, con una narración que aspira a ser leída por cualquier colombiano interesado en entender de dónde vienen los pueblos del piedemonte llanero araucano, por qué desaparecen y cómo resisten. Esa vocación de legibilidad amplia no sacrifica el rigor: cada afirmación relevante está respaldada por fuentes primarias o secundarias debidamente citadas.\\n\\nLa estructura del libro sigue un orden cronológico que parte del tiempo prehispánico y llega hasta el presente, pero no es una historia lineal en el sentido convencional: los autores vuelven sobre los mismos hechos desde ángulos distintos, acumulando capas de comprensión que revelan, al final, la complejidad de un territorio que ha sido al mismo tiempo víctima y protagonista de la historia colombiana." },
    { orden: 3, volumen: "Vol. I", titulo: "Los orígenes de Tame", subtitulo: "Desde la ciudad colonial «La Palma de Espinosa» (1629) al Pueblo de Indios y Parroquia de Nuestra Señora de Tame (1661)", tipo: "Historia colonial", texto_lomo: "LOS ORÍGENES DE TAME", portada: I + "libro-origenes.jpeg", contraportada: I + "libro-origenes-back.jpeg", lomo: I + "lomo-origenes.jpeg", color_lomo: "#6b2a91", color_tinta_lomo: "#f4d83a", grosor: 22, autores: "Luis Milciades Pérez González, Julio César Lamus Gélvez y Giovanni Zorro López.", descripcion: "«Los orígenes de Tame» narra el fascinante proceso de conquista y fundación de una de las primeras ciudades hispánicas en el piedemonte llanero, La Palma de Espinosa, establecida en 1629. A través de un riguroso análisis histórico, esta obra explora la evolución de esta región, desde su transformación en pueblo de indios hasta la erección de la Parroquia Nuestra Señora de Tame en 1661, revelando los desafíos, las dinámicas culturales y los aportes de sus habitantes en la construcción de su identidad.\n\nEsta obra es el resultado del trabajo académico y cultural realizado por los investigadores Julio César Lamus Gélvez, Luis Milcíades Pérez González y Giovanni Zorro López, miembros de la Corporación Tame, Historia y Cultura, dentro de su línea de investigación TAME, 400 AÑOS. Con un enfoque interdisciplinario, esta investigación conmemora y preserva la memoria histórica de la región, ofreciendo una valiosa contribución al entendimiento de sus raíces y de su papel en el contexto histórico de Colombia." },
    { orden: 4, volumen: null, titulo: "La ciudad La Palma de Espinosa", subtitulo: "Capitulación del capitán Alonso Pérez de Guzmán, pleitos por la conquista de territorios, reducción de indios y orígenes de Tame", tipo: "Historia de la conquista", texto_lomo: "LA CIUDAD LA PALMA DE ESPINOSA", portada: I + "libro-palma.jpeg", contraportada: I + "libro-palma-back.jpeg", lomo: I + "lomo-palma.jpeg", color_lomo: "#2f8a2c", color_tinta_lomo: "#ffffff", grosor: 14, autores: "Julio César Lamus Gélvez.", descripcion: "El examen de los orígenes del poblamiento y la fundación de Tame debe partir de la de Palma de Espinosa, una ciudad fundada por el capitán Alonso Pérez de Guzmán. Efectivamente, este firmó con el presidente Juan de Borja el 28 de enero de 1628 una capitulación para descubrir y poblar una parte de los llanos de la provincia de Casanare. Vino entonces al mundo político la ciudad titulada «La Palma de Espinosa», el 18 de febrero de 1629, y además ayudó a reducir, dos años después, indios Tunebos y Giraras en un asentamiento llamado Tame.\n\nTame lo ayudaría a poblar después Pérez de Guzmán con indios Giraras, Tunebos o Tames, dos años después del incendio de Palmas de Espinosa provocado por los Giraras, estableciendo 18 caneyes o casas grandes y juntando 450 indígenas a media legua de la anterior fundación.\n\nTame derivó su nombre del cacique Tambria, un cacique Tunebo que habitó la parte alta del río Tambria o Tame, y tanto encomenderos españoles como jesuitas en desuso convirtieron el vocablo en Tame, que en lengua ancestral significa «hombre de tierra alta, cordillera alta o agua fría».\n\n«¡Todos somos! Y tendremos un nuevo “compromiso en serio”, lo que en democracia es apoyar un proyecto regional importante: la prosperidad regional para los araucanos». — Nixon Bareño Martínez" },
    { orden: 5, volumen: null, titulo: "Los jagüeyes", subtitulo: "Una historia de patrimonio y nostalgias", tipo: "Patrimonio y memoria", texto_lomo: "LOS JAGÜEYES", portada: I + "libro-jagueyes.jpeg", contraportada: I + "libro-jagueyes-back.jpeg", lomo: null, color_lomo: "#f1ece6", color_tinta_lomo: "#8a1f24", grosor: 16, autores: "Julio César Lamus Gélvez.", descripcion: "Desde El Encanto al Crismao\nhabía una sabana larga\ncon un viento atravesao\nque le daba fresco al agua.\n— JCLG / 24\n\n«Surtidores de agua fresca\nGualabao y la Itibana,\ncañitos de ensoñación\ny en sus aguas cristalinas\ncanta la musa llanera\nlos versos de esta canción».\n— Alain Ríos Montilla\n\nLos jagüeyes de mi pueblo\neran la fuente bendita\ncomo si allá desde el cielo\nnos dieran agua clarita.\n— Juan Jacobo Carrizales C.\n\nSe bañaba en El Encanto\npero cuando era bien niña\nBolívar la fue falseando.\nAniceta Cotoarruma.\n— Gustavo Macualo Jácome" }
  ]
};
